# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e9c98b46c0e9bfa4afc638c43079a4e129eb5c5b132bdb19b8dfd857b7d627c7e90deb9563604f74230b9711cd3b4c2642c0bf06f487b1673d4382361500a1
  league_api_key: <%= ENV["LEAGUE_API_KEY"] %>
  paypal_cert_hq: <%= ENV["PAYPAL_CERT_HQ"] %>
  paypal_email: <%= ENV["PAYPAL_EMAIL"] %>

test:
  secret_key_base: 2784df2e07c80a6c68c5a3e334445332b39fe2139053237f7cd98be857ad98210b7361798045bcdc620684d9f29d546ad14f3f48bac08b69bbe38e95e37c51b5
  league_api_key: <%= ENV["LEAGUE_API_KEY"] %>
  paypal_cert_hq: <%= ENV["PAYPAL_CERT_HQ"] %>
  paypal_email: <%= ENV["PAYPAL_EMAIL"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  league_api_key: <%= ENV["LEAGUE_API_KEY"] %>
  paypal_cert_hq: <%= ENV["PAYPAL_CERT_HQ"] %>
  paypal_email: <%= ENV["PAYPAL_EMAIL"] %>
  app_cert: <%= ENV["APP_CERT"] %>
  app_key: <%= ENV["APP_KEY"] %>
  paypal_cert: <%= ENV["PAYPAL_CERT"] %>